# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2005D(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, order_id: str=None):  # noqa: E501
        """InlineResponse2005D - a model defined in Swagger

        :param order_id: The order_id of this InlineResponse2005D.  # noqa: E501
        :type order_id: str
        """
        self.swagger_types = {
            'order_id': str
        }

        self.attribute_map = {
            'order_id': 'orderId'
        }

        self._order_id = order_id

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2005D':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_5_d of this InlineResponse2005D.  # noqa: E501
        :rtype: InlineResponse2005D
        """
        return util.deserialize_model(dikt, cls)

    @property
    def order_id(self) -> str:
        """Gets the order_id of this InlineResponse2005D.


        :return: The order_id of this InlineResponse2005D.
        :rtype: str
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id: str):
        """Sets the order_id of this InlineResponse2005D.


        :param order_id: The order_id of this InlineResponse2005D.
        :type order_id: str
        """

        self._order_id = order_id
