# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class OrderDuration(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, type: str=None, datetime: float=None):  # noqa: E501
        """OrderDuration - a model defined in Swagger

        :param type: The type of this OrderDuration.  # noqa: E501
        :type type: str
        :param datetime: The datetime of this OrderDuration.  # noqa: E501
        :type datetime: float
        """
        self.swagger_types = {
            'type': str,
            'datetime': float
        }

        self.attribute_map = {
            'type': 'type',
            'datetime': 'datetime'
        }

        self._type = type
        self._datetime = datetime

    @classmethod
    def from_dict(cls, dikt) -> 'OrderDuration':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Order_duration of this OrderDuration.  # noqa: E501
        :rtype: OrderDuration
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this OrderDuration.

        Duration ID. Internal ID that you set in ConfigResponse.  # noqa: E501

        :return: The type of this OrderDuration.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this OrderDuration.

        Duration ID. Internal ID that you set in ConfigResponse.  # noqa: E501

        :param type: The type of this OrderDuration.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def datetime(self) -> float:
        """Gets the datetime of this OrderDuration.

        Unit timestamp (UTC).  # noqa: E501

        :return: The datetime of this OrderDuration.
        :rtype: float
        """
        return self._datetime

    @datetime.setter
    def datetime(self, datetime: float):
        """Sets the datetime of this OrderDuration.

        Unit timestamp (UTC).  # noqa: E501

        :param datetime: The datetime of this OrderDuration.
        :type datetime: float
        """

        self._datetime = datetime
